name: Build worksheets
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build worksheets
        uses: k-pet-group/strypify-actions/.github/workflows/build-and-publish-worksheets@main
