name: Build worksheets
on:
  push:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  Build:
    uses: k-pet-group/strypify-actions/.github/workflows/build-and-publish-worksheets.yml@main
